### ISSUE TITLE
No ckan entries

### ISSUE THREAD

**Issue by spirritus** [BobPalmer/MKS#907]
Hi there, 
since the 1.1.3 update there are no ckan entries for all usi related things anymore ...
please fix :-)

cheers

**Comment by JPMaster99** [comment]
Yeah CKAN is giving me an error.
Pleasee fix

**Comment by BobPalmer** [comment]
@JPMaster99 - this was fixed ages ago.

**Comment by JPMaster99** [comment]
I am still getting a exception called CKAN.ModuleNotFoundKraken 

I don't know what that is and it does not let me download the USI mods

**Comment by JPMaster99** [comment]
@BobPalmer
